// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: automation_contract.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AetherLink.Contracts.Automation {

  /// <summary>Holder for reflection information generated from automation_contract.proto</summary>
  public static partial class AutomationContractReflection {

    #region Descriptor
    /// <summary>File descriptor for automation_contract.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AutomationContractReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlhdXRvbWF0aW9uX2NvbnRyYWN0LnByb3RvEgphdXRvbWF0aW9uGg9hZWxm",
            "L2NvcmUucHJvdG8aEmFlbGYvb3B0aW9ucy5wcm90bxoLYWNzMTIucHJvdG8a",
            "G2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoeZ29vZ2xlL3Byb3RvYnVm",
            "L3dyYXBwZXJzLnByb3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnBy",
            "b3RvIpEBCg9Jbml0aWFsaXplSW5wdXQSHAoFYWRtaW4YASABKAsyDS5hZWxm",
            "LkFkZHJlc3MSHQoVYXV0b21hdGlvbl90eXBlX2luZGV4GAIgASgFEh0KBm9y",
            "YWNsZRgDIAEoCzINLmFlbGYuQWRkcmVzcxIiChphdXRvbWF0aW9uX2N1cnJl",
            "bnRfdmVyc2lvbhgEIAEoAyLMAQoTUmVnaXN0ZXJVcGtlZXBJbnB1dBIMCgRu",
            "YW1lGAEgASgJEiYKD3Vwa2VlcF9jb250cmFjdBgCIAEoCzINLmFlbGYuQWRk",
            "cmVzcxIkCg1hZG1pbl9hZGRyZXNzGAMgASgLMg0uYWVsZi5BZGRyZXNzEi0K",
            "DHRyaWdnZXJfdHlwZRgEIAEoDjIXLmF1dG9tYXRpb24uVHJpZ2dlclR5cGUS",
            "FAoMdHJpZ2dlcl9kYXRhGAUgASgMEhQKDHBlcmZvcm1fZGF0YRgGIAEoDCKc",
            "AQoQVXBrZWVwUmVnaXN0ZXJlZBIMCgRuYW1lGAEgASgJEiYKD3Vwa2VlcF9j",
            "b250cmFjdBgCIAEoCzINLmFlbGYuQWRkcmVzcxIdCgl1cGtlZXBfaWQYAyAB",
            "KAsyCi5hZWxmLkhhc2gSLQoMdHJpZ2dlcl90eXBlGAQgASgOMhcuYXV0b21h",
            "dGlvbi5UcmlnZ2VyVHlwZToEoLsYASKXAQoKVXBrZWVwSW5mbxIMCgRuYW1l",
            "GAEgASgJEiYKD3Vwa2VlcF9jb250cmFjdBgCIAEoCzINLmFlbGYuQWRkcmVz",
            "cxIkCg1hZG1pbl9hZGRyZXNzGAMgASgLMg0uYWVsZi5BZGRyZXNzEi0KDHRy",
            "aWdnZXJfdHlwZRgEIAEoDjIXLmF1dG9tYXRpb24uVHJpZ2dlclR5cGUiigEK",
            "BkNvbmZpZxIfChdyZXF1ZXN0X3RpbWVvdXRfc2Vjb25kcxgBIAEoAxIlCh1t",
            "aW5pbXVtX3JlcXVlc3RfY29uZmlybWF0aW9ucxgCIAEoAxIhChltYXhfcmVx",
            "dWVzdF9jb25maXJtYXRpb25zGAMgASgDEhUKDW1heF9udW1fd29yZHMYBCAB",
            "KAMiNwoTUmVxdWVzdFR5cGVJbmRleFNldBIaChJyZXF1ZXN0X3R5cGVfaW5k",
            "ZXgYASABKAU6BKC7GAEiNAoNVXBrZWVwUmVtb3ZlZBIdCgl1cGtlZXBfaWQY",
            "ASABKAsyCi5hZWxmLkhhc2g6BKC7GAEieQoLUmVwb3J0SW5wdXQSIgoLdHJh",
            "bnNtaXR0ZXIYASABKAsyDS5hZWxmLkFkZHJlc3MSIgoOcmVwb3J0X2NvbnRl",
            "eHQYAiADKAsyCi5hZWxmLkhhc2gSDgoGcmVwb3J0GAMgASgMEhIKCnNpZ25h",
            "dHVyZXMYBCADKAwiNgoPVXBrZWVwUGVyZm9ybWVkEh0KCXVwa2VlcF9pZBgB",
            "IAEoCzIKLmFlbGYuSGFzaDoEoLsYASogCgtUcmlnZ2VyVHlwZRIICgRDcm9u",
            "EAASBwoDTG9nEAEygggKEkF1dG9tYXRpb25Db250cmFjdBJLCg5SZWdpc3Rl",
            "clVwa2VlcBIfLmF1dG9tYXRpb24uUmVnaXN0ZXJVcGtlZXBJbnB1dBoWLmdv",
            "b2dsZS5wcm90b2J1Zi5FbXB0eSIAEjgKEERlcmVnaXN0ZXJVcGtlZXASCi5h",
            "ZWxmLkhhc2gaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJDCgpJbml0aWFs",
            "aXplEhsuYXV0b21hdGlvbi5Jbml0aWFsaXplSW5wdXQaFi5nb29nbGUucHJv",
            "dG9idWYuRW1wdHkiABI5CgVQYXVzZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEjsKB1VucGF1c2USFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJD",
            "ChhTZXRPcmFjbGVDb250cmFjdEFkZHJlc3MSDS5hZWxmLkFkZHJlc3MaFi5n",
            "b29nbGUucHJvdG9idWYuRW1wdHkiABJMChNTZXRSZXF1ZXN0VHlwZUluZGV4",
            "EhsuZ29vZ2xlLnByb3RvYnVmLkludDMyVmFsdWUaFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkiABI7CgZSZXBvcnQSFy5hdXRvbWF0aW9uLlJlcG9ydElucHV0",
            "GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgASOAoQRGVsZXRlQ29tbWl0bWVu",
            "dBIKLmFlbGYuSGFzaBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEjgKCEdl",
            "dEFkbWluEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Gg0uYWVsZi5BZGRyZXNz",
            "IgWIifcBARJFCghJc1BhdXNlZBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoa",
            "Lmdvb2dsZS5wcm90b2J1Zi5Cb29sVmFsdWUiBYiJ9wEBEkgKGEdldE9yYWNs",
            "ZUNvbnRyYWN0QWRkcmVzcxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoNLmFl",
            "bGYuQWRkcmVzcyIFiIn3AQESUQoTR2V0UmVxdWVzdFR5cGVJbmRleBIWLmdv",
            "b2dsZS5wcm90b2J1Zi5FbXB0eRobLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZh",
            "bHVlIgWIifcBARIyChFHZXRDb21taXRtZW50SGFzaBIKLmFlbGYuSGFzaBoK",
            "LmFlbGYuSGFzaCIFiIn3AQEaTMrK9gELYWNzMTIucHJvdG+yzPYBN0FldGhl",
            "ckxpbmsuQ29udHJhY3RzLkF1dG9tYXRpb24uQXV0b21hdGlvbkNvbnRyYWN0",
            "U3RhdGVCIqoCH0FldGhlckxpbmsuQ29udHJhY3RzLkF1dG9tYXRpb25iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Types.CoreReflection.Descriptor, global::AElf.OptionsReflection.Descriptor, global::AElf.Standards.ACS12.Acs12Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AetherLink.Contracts.Automation.TriggerType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.InitializeInput), global::AetherLink.Contracts.Automation.InitializeInput.Parser, new[]{ "Admin", "AutomationTypeIndex", "Oracle", "AutomationCurrentVersion" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.RegisterUpkeepInput), global::AetherLink.Contracts.Automation.RegisterUpkeepInput.Parser, new[]{ "Name", "UpkeepContract", "AdminAddress", "TriggerType", "TriggerData", "PerformData" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.UpkeepRegistered), global::AetherLink.Contracts.Automation.UpkeepRegistered.Parser, new[]{ "Name", "UpkeepContract", "UpkeepId", "TriggerType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.UpkeepInfo), global::AetherLink.Contracts.Automation.UpkeepInfo.Parser, new[]{ "Name", "UpkeepContract", "AdminAddress", "TriggerType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.Config), global::AetherLink.Contracts.Automation.Config.Parser, new[]{ "RequestTimeoutSeconds", "MinimumRequestConfirmations", "MaxRequestConfirmations", "MaxNumWords" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.RequestTypeIndexSet), global::AetherLink.Contracts.Automation.RequestTypeIndexSet.Parser, new[]{ "RequestTypeIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.UpkeepRemoved), global::AetherLink.Contracts.Automation.UpkeepRemoved.Parser, new[]{ "UpkeepId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.ReportInput), global::AetherLink.Contracts.Automation.ReportInput.Parser, new[]{ "Transmitter", "ReportContext", "Report", "Signatures" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AetherLink.Contracts.Automation.UpkeepPerformed), global::AetherLink.Contracts.Automation.UpkeepPerformed.Parser, new[]{ "UpkeepId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TriggerType {
    [pbr::OriginalName("Cron")] Cron = 0,
    [pbr::OriginalName("Log")] Log = 1,
  }

  #endregion

  #region Messages
  public sealed partial class InitializeInput : pb::IMessage<InitializeInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InitializeInput> _parser = new pb::MessageParser<InitializeInput>(() => new InitializeInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InitializeInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeInput(InitializeInput other) : this() {
      admin_ = other.admin_ != null ? other.admin_.Clone() : null;
      automationTypeIndex_ = other.automationTypeIndex_;
      oracle_ = other.oracle_ != null ? other.oracle_.Clone() : null;
      automationCurrentVersion_ = other.automationCurrentVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InitializeInput Clone() {
      return new InitializeInput(this);
    }

    /// <summary>Field number for the "admin" field.</summary>
    public const int AdminFieldNumber = 1;
    private global::AElf.Types.Address admin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Admin {
      get { return admin_; }
      set {
        admin_ = value;
      }
    }

    /// <summary>Field number for the "automation_type_index" field.</summary>
    public const int AutomationTypeIndexFieldNumber = 2;
    private int automationTypeIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AutomationTypeIndex {
      get { return automationTypeIndex_; }
      set {
        automationTypeIndex_ = value;
      }
    }

    /// <summary>Field number for the "oracle" field.</summary>
    public const int OracleFieldNumber = 3;
    private global::AElf.Types.Address oracle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Oracle {
      get { return oracle_; }
      set {
        oracle_ = value;
      }
    }

    /// <summary>Field number for the "automation_current_version" field.</summary>
    public const int AutomationCurrentVersionFieldNumber = 4;
    private long automationCurrentVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AutomationCurrentVersion {
      get { return automationCurrentVersion_; }
      set {
        automationCurrentVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InitializeInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InitializeInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Admin, other.Admin)) return false;
      if (AutomationTypeIndex != other.AutomationTypeIndex) return false;
      if (!object.Equals(Oracle, other.Oracle)) return false;
      if (AutomationCurrentVersion != other.AutomationCurrentVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (admin_ != null) hash ^= Admin.GetHashCode();
      if (AutomationTypeIndex != 0) hash ^= AutomationTypeIndex.GetHashCode();
      if (oracle_ != null) hash ^= Oracle.GetHashCode();
      if (AutomationCurrentVersion != 0L) hash ^= AutomationCurrentVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (admin_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Admin);
      }
      if (AutomationTypeIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AutomationTypeIndex);
      }
      if (oracle_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Oracle);
      }
      if (AutomationCurrentVersion != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(AutomationCurrentVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (admin_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Admin);
      }
      if (AutomationTypeIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AutomationTypeIndex);
      }
      if (oracle_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Oracle);
      }
      if (AutomationCurrentVersion != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(AutomationCurrentVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (admin_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Admin);
      }
      if (AutomationTypeIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AutomationTypeIndex);
      }
      if (oracle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Oracle);
      }
      if (AutomationCurrentVersion != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AutomationCurrentVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InitializeInput other) {
      if (other == null) {
        return;
      }
      if (other.admin_ != null) {
        if (admin_ == null) {
          Admin = new global::AElf.Types.Address();
        }
        Admin.MergeFrom(other.Admin);
      }
      if (other.AutomationTypeIndex != 0) {
        AutomationTypeIndex = other.AutomationTypeIndex;
      }
      if (other.oracle_ != null) {
        if (oracle_ == null) {
          Oracle = new global::AElf.Types.Address();
        }
        Oracle.MergeFrom(other.Oracle);
      }
      if (other.AutomationCurrentVersion != 0L) {
        AutomationCurrentVersion = other.AutomationCurrentVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (admin_ == null) {
              Admin = new global::AElf.Types.Address();
            }
            input.ReadMessage(Admin);
            break;
          }
          case 16: {
            AutomationTypeIndex = input.ReadInt32();
            break;
          }
          case 26: {
            if (oracle_ == null) {
              Oracle = new global::AElf.Types.Address();
            }
            input.ReadMessage(Oracle);
            break;
          }
          case 32: {
            AutomationCurrentVersion = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (admin_ == null) {
              Admin = new global::AElf.Types.Address();
            }
            input.ReadMessage(Admin);
            break;
          }
          case 16: {
            AutomationTypeIndex = input.ReadInt32();
            break;
          }
          case 26: {
            if (oracle_ == null) {
              Oracle = new global::AElf.Types.Address();
            }
            input.ReadMessage(Oracle);
            break;
          }
          case 32: {
            AutomationCurrentVersion = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RegisterUpkeepInput : pb::IMessage<RegisterUpkeepInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RegisterUpkeepInput> _parser = new pb::MessageParser<RegisterUpkeepInput>(() => new RegisterUpkeepInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RegisterUpkeepInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterUpkeepInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterUpkeepInput(RegisterUpkeepInput other) : this() {
      name_ = other.name_;
      upkeepContract_ = other.upkeepContract_ != null ? other.upkeepContract_.Clone() : null;
      adminAddress_ = other.adminAddress_ != null ? other.adminAddress_.Clone() : null;
      triggerType_ = other.triggerType_;
      triggerData_ = other.triggerData_;
      performData_ = other.performData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RegisterUpkeepInput Clone() {
      return new RegisterUpkeepInput(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "upkeep_contract" field.</summary>
    public const int UpkeepContractFieldNumber = 2;
    private global::AElf.Types.Address upkeepContract_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address UpkeepContract {
      get { return upkeepContract_; }
      set {
        upkeepContract_ = value;
      }
    }

    /// <summary>Field number for the "admin_address" field.</summary>
    public const int AdminAddressFieldNumber = 3;
    private global::AElf.Types.Address adminAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address AdminAddress {
      get { return adminAddress_; }
      set {
        adminAddress_ = value;
      }
    }

    /// <summary>Field number for the "trigger_type" field.</summary>
    public const int TriggerTypeFieldNumber = 4;
    private global::AetherLink.Contracts.Automation.TriggerType triggerType_ = global::AetherLink.Contracts.Automation.TriggerType.Cron;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AetherLink.Contracts.Automation.TriggerType TriggerType {
      get { return triggerType_; }
      set {
        triggerType_ = value;
      }
    }

    /// <summary>Field number for the "trigger_data" field.</summary>
    public const int TriggerDataFieldNumber = 5;
    private pb::ByteString triggerData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString TriggerData {
      get { return triggerData_; }
      set {
        triggerData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "perform_data" field.</summary>
    public const int PerformDataFieldNumber = 6;
    private pb::ByteString performData_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString PerformData {
      get { return performData_; }
      set {
        performData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RegisterUpkeepInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RegisterUpkeepInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(UpkeepContract, other.UpkeepContract)) return false;
      if (!object.Equals(AdminAddress, other.AdminAddress)) return false;
      if (TriggerType != other.TriggerType) return false;
      if (TriggerData != other.TriggerData) return false;
      if (PerformData != other.PerformData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (upkeepContract_ != null) hash ^= UpkeepContract.GetHashCode();
      if (adminAddress_ != null) hash ^= AdminAddress.GetHashCode();
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) hash ^= TriggerType.GetHashCode();
      if (TriggerData.Length != 0) hash ^= TriggerData.GetHashCode();
      if (PerformData.Length != 0) hash ^= PerformData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (upkeepContract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpkeepContract);
      }
      if (adminAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AdminAddress);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TriggerType);
      }
      if (TriggerData.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(TriggerData);
      }
      if (PerformData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(PerformData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (upkeepContract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpkeepContract);
      }
      if (adminAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AdminAddress);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TriggerType);
      }
      if (TriggerData.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(TriggerData);
      }
      if (PerformData.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(PerformData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (upkeepContract_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpkeepContract);
      }
      if (adminAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AdminAddress);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TriggerType);
      }
      if (TriggerData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TriggerData);
      }
      if (PerformData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PerformData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RegisterUpkeepInput other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.upkeepContract_ != null) {
        if (upkeepContract_ == null) {
          UpkeepContract = new global::AElf.Types.Address();
        }
        UpkeepContract.MergeFrom(other.UpkeepContract);
      }
      if (other.adminAddress_ != null) {
        if (adminAddress_ == null) {
          AdminAddress = new global::AElf.Types.Address();
        }
        AdminAddress.MergeFrom(other.AdminAddress);
      }
      if (other.TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        TriggerType = other.TriggerType;
      }
      if (other.TriggerData.Length != 0) {
        TriggerData = other.TriggerData;
      }
      if (other.PerformData.Length != 0) {
        PerformData = other.PerformData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (upkeepContract_ == null) {
              UpkeepContract = new global::AElf.Types.Address();
            }
            input.ReadMessage(UpkeepContract);
            break;
          }
          case 26: {
            if (adminAddress_ == null) {
              AdminAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(AdminAddress);
            break;
          }
          case 32: {
            TriggerType = (global::AetherLink.Contracts.Automation.TriggerType) input.ReadEnum();
            break;
          }
          case 42: {
            TriggerData = input.ReadBytes();
            break;
          }
          case 50: {
            PerformData = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (upkeepContract_ == null) {
              UpkeepContract = new global::AElf.Types.Address();
            }
            input.ReadMessage(UpkeepContract);
            break;
          }
          case 26: {
            if (adminAddress_ == null) {
              AdminAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(AdminAddress);
            break;
          }
          case 32: {
            TriggerType = (global::AetherLink.Contracts.Automation.TriggerType) input.ReadEnum();
            break;
          }
          case 42: {
            TriggerData = input.ReadBytes();
            break;
          }
          case 50: {
            PerformData = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpkeepRegistered : pb::IMessage<UpkeepRegistered>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpkeepRegistered> _parser = new pb::MessageParser<UpkeepRegistered>(() => new UpkeepRegistered());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpkeepRegistered> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepRegistered() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepRegistered(UpkeepRegistered other) : this() {
      name_ = other.name_;
      upkeepContract_ = other.upkeepContract_ != null ? other.upkeepContract_.Clone() : null;
      upkeepId_ = other.upkeepId_ != null ? other.upkeepId_.Clone() : null;
      triggerType_ = other.triggerType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepRegistered Clone() {
      return new UpkeepRegistered(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "upkeep_contract" field.</summary>
    public const int UpkeepContractFieldNumber = 2;
    private global::AElf.Types.Address upkeepContract_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address UpkeepContract {
      get { return upkeepContract_; }
      set {
        upkeepContract_ = value;
      }
    }

    /// <summary>Field number for the "upkeep_id" field.</summary>
    public const int UpkeepIdFieldNumber = 3;
    private global::AElf.Types.Hash upkeepId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Hash UpkeepId {
      get { return upkeepId_; }
      set {
        upkeepId_ = value;
      }
    }

    /// <summary>Field number for the "trigger_type" field.</summary>
    public const int TriggerTypeFieldNumber = 4;
    private global::AetherLink.Contracts.Automation.TriggerType triggerType_ = global::AetherLink.Contracts.Automation.TriggerType.Cron;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AetherLink.Contracts.Automation.TriggerType TriggerType {
      get { return triggerType_; }
      set {
        triggerType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpkeepRegistered);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpkeepRegistered other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(UpkeepContract, other.UpkeepContract)) return false;
      if (!object.Equals(UpkeepId, other.UpkeepId)) return false;
      if (TriggerType != other.TriggerType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (upkeepContract_ != null) hash ^= UpkeepContract.GetHashCode();
      if (upkeepId_ != null) hash ^= UpkeepId.GetHashCode();
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) hash ^= TriggerType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (upkeepContract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpkeepContract);
      }
      if (upkeepId_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpkeepId);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TriggerType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (upkeepContract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpkeepContract);
      }
      if (upkeepId_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpkeepId);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TriggerType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (upkeepContract_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpkeepContract);
      }
      if (upkeepId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpkeepId);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TriggerType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpkeepRegistered other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.upkeepContract_ != null) {
        if (upkeepContract_ == null) {
          UpkeepContract = new global::AElf.Types.Address();
        }
        UpkeepContract.MergeFrom(other.UpkeepContract);
      }
      if (other.upkeepId_ != null) {
        if (upkeepId_ == null) {
          UpkeepId = new global::AElf.Types.Hash();
        }
        UpkeepId.MergeFrom(other.UpkeepId);
      }
      if (other.TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        TriggerType = other.TriggerType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (upkeepContract_ == null) {
              UpkeepContract = new global::AElf.Types.Address();
            }
            input.ReadMessage(UpkeepContract);
            break;
          }
          case 26: {
            if (upkeepId_ == null) {
              UpkeepId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(UpkeepId);
            break;
          }
          case 32: {
            TriggerType = (global::AetherLink.Contracts.Automation.TriggerType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (upkeepContract_ == null) {
              UpkeepContract = new global::AElf.Types.Address();
            }
            input.ReadMessage(UpkeepContract);
            break;
          }
          case 26: {
            if (upkeepId_ == null) {
              UpkeepId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(UpkeepId);
            break;
          }
          case 32: {
            TriggerType = (global::AetherLink.Contracts.Automation.TriggerType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpkeepInfo : pb::IMessage<UpkeepInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpkeepInfo> _parser = new pb::MessageParser<UpkeepInfo>(() => new UpkeepInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpkeepInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepInfo(UpkeepInfo other) : this() {
      name_ = other.name_;
      upkeepContract_ = other.upkeepContract_ != null ? other.upkeepContract_.Clone() : null;
      adminAddress_ = other.adminAddress_ != null ? other.adminAddress_.Clone() : null;
      triggerType_ = other.triggerType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepInfo Clone() {
      return new UpkeepInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "upkeep_contract" field.</summary>
    public const int UpkeepContractFieldNumber = 2;
    private global::AElf.Types.Address upkeepContract_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address UpkeepContract {
      get { return upkeepContract_; }
      set {
        upkeepContract_ = value;
      }
    }

    /// <summary>Field number for the "admin_address" field.</summary>
    public const int AdminAddressFieldNumber = 3;
    private global::AElf.Types.Address adminAddress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address AdminAddress {
      get { return adminAddress_; }
      set {
        adminAddress_ = value;
      }
    }

    /// <summary>Field number for the "trigger_type" field.</summary>
    public const int TriggerTypeFieldNumber = 4;
    private global::AetherLink.Contracts.Automation.TriggerType triggerType_ = global::AetherLink.Contracts.Automation.TriggerType.Cron;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AetherLink.Contracts.Automation.TriggerType TriggerType {
      get { return triggerType_; }
      set {
        triggerType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpkeepInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpkeepInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(UpkeepContract, other.UpkeepContract)) return false;
      if (!object.Equals(AdminAddress, other.AdminAddress)) return false;
      if (TriggerType != other.TriggerType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (upkeepContract_ != null) hash ^= UpkeepContract.GetHashCode();
      if (adminAddress_ != null) hash ^= AdminAddress.GetHashCode();
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) hash ^= TriggerType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (upkeepContract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpkeepContract);
      }
      if (adminAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AdminAddress);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TriggerType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (upkeepContract_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UpkeepContract);
      }
      if (adminAddress_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(AdminAddress);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TriggerType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (upkeepContract_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpkeepContract);
      }
      if (adminAddress_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AdminAddress);
      }
      if (TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TriggerType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpkeepInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.upkeepContract_ != null) {
        if (upkeepContract_ == null) {
          UpkeepContract = new global::AElf.Types.Address();
        }
        UpkeepContract.MergeFrom(other.UpkeepContract);
      }
      if (other.adminAddress_ != null) {
        if (adminAddress_ == null) {
          AdminAddress = new global::AElf.Types.Address();
        }
        AdminAddress.MergeFrom(other.AdminAddress);
      }
      if (other.TriggerType != global::AetherLink.Contracts.Automation.TriggerType.Cron) {
        TriggerType = other.TriggerType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (upkeepContract_ == null) {
              UpkeepContract = new global::AElf.Types.Address();
            }
            input.ReadMessage(UpkeepContract);
            break;
          }
          case 26: {
            if (adminAddress_ == null) {
              AdminAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(AdminAddress);
            break;
          }
          case 32: {
            TriggerType = (global::AetherLink.Contracts.Automation.TriggerType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (upkeepContract_ == null) {
              UpkeepContract = new global::AElf.Types.Address();
            }
            input.ReadMessage(UpkeepContract);
            break;
          }
          case 26: {
            if (adminAddress_ == null) {
              AdminAddress = new global::AElf.Types.Address();
            }
            input.ReadMessage(AdminAddress);
            break;
          }
          case 32: {
            TriggerType = (global::AetherLink.Contracts.Automation.TriggerType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Config : pb::IMessage<Config>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Config> _parser = new pb::MessageParser<Config>(() => new Config());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Config> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config(Config other) : this() {
      requestTimeoutSeconds_ = other.requestTimeoutSeconds_;
      minimumRequestConfirmations_ = other.minimumRequestConfirmations_;
      maxRequestConfirmations_ = other.maxRequestConfirmations_;
      maxNumWords_ = other.maxNumWords_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Config Clone() {
      return new Config(this);
    }

    /// <summary>Field number for the "request_timeout_seconds" field.</summary>
    public const int RequestTimeoutSecondsFieldNumber = 1;
    private long requestTimeoutSeconds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RequestTimeoutSeconds {
      get { return requestTimeoutSeconds_; }
      set {
        requestTimeoutSeconds_ = value;
      }
    }

    /// <summary>Field number for the "minimum_request_confirmations" field.</summary>
    public const int MinimumRequestConfirmationsFieldNumber = 2;
    private long minimumRequestConfirmations_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MinimumRequestConfirmations {
      get { return minimumRequestConfirmations_; }
      set {
        minimumRequestConfirmations_ = value;
      }
    }

    /// <summary>Field number for the "max_request_confirmations" field.</summary>
    public const int MaxRequestConfirmationsFieldNumber = 3;
    private long maxRequestConfirmations_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MaxRequestConfirmations {
      get { return maxRequestConfirmations_; }
      set {
        maxRequestConfirmations_ = value;
      }
    }

    /// <summary>Field number for the "max_num_words" field.</summary>
    public const int MaxNumWordsFieldNumber = 4;
    private long maxNumWords_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long MaxNumWords {
      get { return maxNumWords_; }
      set {
        maxNumWords_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Config);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Config other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestTimeoutSeconds != other.RequestTimeoutSeconds) return false;
      if (MinimumRequestConfirmations != other.MinimumRequestConfirmations) return false;
      if (MaxRequestConfirmations != other.MaxRequestConfirmations) return false;
      if (MaxNumWords != other.MaxNumWords) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestTimeoutSeconds != 0L) hash ^= RequestTimeoutSeconds.GetHashCode();
      if (MinimumRequestConfirmations != 0L) hash ^= MinimumRequestConfirmations.GetHashCode();
      if (MaxRequestConfirmations != 0L) hash ^= MaxRequestConfirmations.GetHashCode();
      if (MaxNumWords != 0L) hash ^= MaxNumWords.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestTimeoutSeconds != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(RequestTimeoutSeconds);
      }
      if (MinimumRequestConfirmations != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MinimumRequestConfirmations);
      }
      if (MaxRequestConfirmations != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MaxRequestConfirmations);
      }
      if (MaxNumWords != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(MaxNumWords);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestTimeoutSeconds != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(RequestTimeoutSeconds);
      }
      if (MinimumRequestConfirmations != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(MinimumRequestConfirmations);
      }
      if (MaxRequestConfirmations != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(MaxRequestConfirmations);
      }
      if (MaxNumWords != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(MaxNumWords);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestTimeoutSeconds != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RequestTimeoutSeconds);
      }
      if (MinimumRequestConfirmations != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MinimumRequestConfirmations);
      }
      if (MaxRequestConfirmations != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MaxRequestConfirmations);
      }
      if (MaxNumWords != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(MaxNumWords);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Config other) {
      if (other == null) {
        return;
      }
      if (other.RequestTimeoutSeconds != 0L) {
        RequestTimeoutSeconds = other.RequestTimeoutSeconds;
      }
      if (other.MinimumRequestConfirmations != 0L) {
        MinimumRequestConfirmations = other.MinimumRequestConfirmations;
      }
      if (other.MaxRequestConfirmations != 0L) {
        MaxRequestConfirmations = other.MaxRequestConfirmations;
      }
      if (other.MaxNumWords != 0L) {
        MaxNumWords = other.MaxNumWords;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestTimeoutSeconds = input.ReadInt64();
            break;
          }
          case 16: {
            MinimumRequestConfirmations = input.ReadInt64();
            break;
          }
          case 24: {
            MaxRequestConfirmations = input.ReadInt64();
            break;
          }
          case 32: {
            MaxNumWords = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RequestTimeoutSeconds = input.ReadInt64();
            break;
          }
          case 16: {
            MinimumRequestConfirmations = input.ReadInt64();
            break;
          }
          case 24: {
            MaxRequestConfirmations = input.ReadInt64();
            break;
          }
          case 32: {
            MaxNumWords = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RequestTypeIndexSet : pb::IMessage<RequestTypeIndexSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestTypeIndexSet> _parser = new pb::MessageParser<RequestTypeIndexSet>(() => new RequestTypeIndexSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestTypeIndexSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTypeIndexSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTypeIndexSet(RequestTypeIndexSet other) : this() {
      requestTypeIndex_ = other.requestTypeIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTypeIndexSet Clone() {
      return new RequestTypeIndexSet(this);
    }

    /// <summary>Field number for the "request_type_index" field.</summary>
    public const int RequestTypeIndexFieldNumber = 1;
    private int requestTypeIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RequestTypeIndex {
      get { return requestTypeIndex_; }
      set {
        requestTypeIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestTypeIndexSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestTypeIndexSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestTypeIndex != other.RequestTypeIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestTypeIndex != 0) hash ^= RequestTypeIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestTypeIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestTypeIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestTypeIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(RequestTypeIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestTypeIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RequestTypeIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestTypeIndexSet other) {
      if (other == null) {
        return;
      }
      if (other.RequestTypeIndex != 0) {
        RequestTypeIndex = other.RequestTypeIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestTypeIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RequestTypeIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpkeepRemoved : pb::IMessage<UpkeepRemoved>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpkeepRemoved> _parser = new pb::MessageParser<UpkeepRemoved>(() => new UpkeepRemoved());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpkeepRemoved> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepRemoved() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepRemoved(UpkeepRemoved other) : this() {
      upkeepId_ = other.upkeepId_ != null ? other.upkeepId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepRemoved Clone() {
      return new UpkeepRemoved(this);
    }

    /// <summary>Field number for the "upkeep_id" field.</summary>
    public const int UpkeepIdFieldNumber = 1;
    private global::AElf.Types.Hash upkeepId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Hash UpkeepId {
      get { return upkeepId_; }
      set {
        upkeepId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpkeepRemoved);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpkeepRemoved other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UpkeepId, other.UpkeepId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (upkeepId_ != null) hash ^= UpkeepId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (upkeepId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpkeepId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (upkeepId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpkeepId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (upkeepId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpkeepId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpkeepRemoved other) {
      if (other == null) {
        return;
      }
      if (other.upkeepId_ != null) {
        if (upkeepId_ == null) {
          UpkeepId = new global::AElf.Types.Hash();
        }
        UpkeepId.MergeFrom(other.UpkeepId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (upkeepId_ == null) {
              UpkeepId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(UpkeepId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (upkeepId_ == null) {
              UpkeepId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(UpkeepId);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ReportInput : pb::IMessage<ReportInput>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReportInput> _parser = new pb::MessageParser<ReportInput>(() => new ReportInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReportInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReportInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReportInput(ReportInput other) : this() {
      transmitter_ = other.transmitter_ != null ? other.transmitter_.Clone() : null;
      reportContext_ = other.reportContext_.Clone();
      report_ = other.report_;
      signatures_ = other.signatures_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReportInput Clone() {
      return new ReportInput(this);
    }

    /// <summary>Field number for the "transmitter" field.</summary>
    public const int TransmitterFieldNumber = 1;
    private global::AElf.Types.Address transmitter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Address Transmitter {
      get { return transmitter_; }
      set {
        transmitter_ = value;
      }
    }

    /// <summary>Field number for the "report_context" field.</summary>
    public const int ReportContextFieldNumber = 2;
    private static readonly pb::FieldCodec<global::AElf.Types.Hash> _repeated_reportContext_codec
        = pb::FieldCodec.ForMessage(18, global::AElf.Types.Hash.Parser);
    private readonly pbc::RepeatedField<global::AElf.Types.Hash> reportContext_ = new pbc::RepeatedField<global::AElf.Types.Hash>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AElf.Types.Hash> ReportContext {
      get { return reportContext_; }
    }

    /// <summary>Field number for the "report" field.</summary>
    public const int ReportFieldNumber = 3;
    private pb::ByteString report_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Report {
      get { return report_; }
      set {
        report_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "signatures" field.</summary>
    public const int SignaturesFieldNumber = 4;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_signatures_codec
        = pb::FieldCodec.ForBytes(34);
    private readonly pbc::RepeatedField<pb::ByteString> signatures_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> Signatures {
      get { return signatures_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReportInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReportInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Transmitter, other.Transmitter)) return false;
      if(!reportContext_.Equals(other.reportContext_)) return false;
      if (Report != other.Report) return false;
      if(!signatures_.Equals(other.signatures_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (transmitter_ != null) hash ^= Transmitter.GetHashCode();
      hash ^= reportContext_.GetHashCode();
      if (Report.Length != 0) hash ^= Report.GetHashCode();
      hash ^= signatures_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (transmitter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Transmitter);
      }
      reportContext_.WriteTo(output, _repeated_reportContext_codec);
      if (Report.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Report);
      }
      signatures_.WriteTo(output, _repeated_signatures_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (transmitter_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Transmitter);
      }
      reportContext_.WriteTo(ref output, _repeated_reportContext_codec);
      if (Report.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Report);
      }
      signatures_.WriteTo(ref output, _repeated_signatures_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (transmitter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Transmitter);
      }
      size += reportContext_.CalculateSize(_repeated_reportContext_codec);
      if (Report.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Report);
      }
      size += signatures_.CalculateSize(_repeated_signatures_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReportInput other) {
      if (other == null) {
        return;
      }
      if (other.transmitter_ != null) {
        if (transmitter_ == null) {
          Transmitter = new global::AElf.Types.Address();
        }
        Transmitter.MergeFrom(other.Transmitter);
      }
      reportContext_.Add(other.reportContext_);
      if (other.Report.Length != 0) {
        Report = other.Report;
      }
      signatures_.Add(other.signatures_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (transmitter_ == null) {
              Transmitter = new global::AElf.Types.Address();
            }
            input.ReadMessage(Transmitter);
            break;
          }
          case 18: {
            reportContext_.AddEntriesFrom(input, _repeated_reportContext_codec);
            break;
          }
          case 26: {
            Report = input.ReadBytes();
            break;
          }
          case 34: {
            signatures_.AddEntriesFrom(input, _repeated_signatures_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (transmitter_ == null) {
              Transmitter = new global::AElf.Types.Address();
            }
            input.ReadMessage(Transmitter);
            break;
          }
          case 18: {
            reportContext_.AddEntriesFrom(ref input, _repeated_reportContext_codec);
            break;
          }
          case 26: {
            Report = input.ReadBytes();
            break;
          }
          case 34: {
            signatures_.AddEntriesFrom(ref input, _repeated_signatures_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class UpkeepPerformed : pb::IMessage<UpkeepPerformed>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpkeepPerformed> _parser = new pb::MessageParser<UpkeepPerformed>(() => new UpkeepPerformed());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpkeepPerformed> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepPerformed() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepPerformed(UpkeepPerformed other) : this() {
      upkeepId_ = other.upkeepId_ != null ? other.upkeepId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpkeepPerformed Clone() {
      return new UpkeepPerformed(this);
    }

    /// <summary>Field number for the "upkeep_id" field.</summary>
    public const int UpkeepIdFieldNumber = 1;
    private global::AElf.Types.Hash upkeepId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AElf.Types.Hash UpkeepId {
      get { return upkeepId_; }
      set {
        upkeepId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpkeepPerformed);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpkeepPerformed other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UpkeepId, other.UpkeepId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (upkeepId_ != null) hash ^= UpkeepId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (upkeepId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpkeepId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (upkeepId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpkeepId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (upkeepId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpkeepId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpkeepPerformed other) {
      if (other == null) {
        return;
      }
      if (other.upkeepId_ != null) {
        if (upkeepId_ == null) {
          UpkeepId = new global::AElf.Types.Hash();
        }
        UpkeepId.MergeFrom(other.UpkeepId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (upkeepId_ == null) {
              UpkeepId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(UpkeepId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (upkeepId_ == null) {
              UpkeepId = new global::AElf.Types.Hash();
            }
            input.ReadMessage(UpkeepId);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
