// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: automation_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AetherLink.Contracts.Automation {

  #region Events
  public partial class UpkeepRegistered : aelf::IEvent<UpkeepRegistered>
  {
    public global::System.Collections.Generic.IEnumerable<UpkeepRegistered> GetIndexed()
    {
      return new List<UpkeepRegistered>
      {
      };
    }

    public UpkeepRegistered GetNonIndexed()
    {
      return new UpkeepRegistered
      {
        Name = Name,
        UpkeepContract = UpkeepContract,
        UpkeepId = UpkeepId,
        TriggerType = TriggerType,
      };
    }
  }

  public partial class RequestTypeIndexSet : aelf::IEvent<RequestTypeIndexSet>
  {
    public global::System.Collections.Generic.IEnumerable<RequestTypeIndexSet> GetIndexed()
    {
      return new List<RequestTypeIndexSet>
      {
      };
    }

    public RequestTypeIndexSet GetNonIndexed()
    {
      return new RequestTypeIndexSet
      {
        RequestTypeIndex = RequestTypeIndex,
      };
    }
  }

  public partial class SubscriptionIdSet : aelf::IEvent<SubscriptionIdSet>
  {
    public global::System.Collections.Generic.IEnumerable<SubscriptionIdSet> GetIndexed()
    {
      return new List<SubscriptionIdSet>
      {
      };
    }

    public SubscriptionIdSet GetNonIndexed()
    {
      return new SubscriptionIdSet
      {
        SubscriptionId = SubscriptionId,
      };
    }
  }

  public partial class UpkeepRemoved : aelf::IEvent<UpkeepRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<UpkeepRemoved> GetIndexed()
    {
      return new List<UpkeepRemoved>
      {
      };
    }

    public UpkeepRemoved GetNonIndexed()
    {
      return new UpkeepRemoved
      {
        UpkeepId = UpkeepId,
      };
    }
  }

  public partial class UpkeepPerformed : aelf::IEvent<UpkeepPerformed>
  {
    public global::System.Collections.Generic.IEnumerable<UpkeepPerformed> GetIndexed()
    {
      return new List<UpkeepPerformed>
      {
      };
    }

    public UpkeepPerformed GetNonIndexed()
    {
      return new UpkeepPerformed
      {
        UpkeepId = UpkeepId,
      };
    }
  }

  #endregion
  /// <summary>
  /// the contract definition: a gRPC service definition.
  /// </summary>
  public static partial class AutomationContractContainer
  {
    static readonly string __ServiceName = "automation.AutomationContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Automation.RegisterUpkeepInput> __Marshaller_automation_RegisterUpkeepInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Automation.RegisterUpkeepInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Automation.UpkeepInfo> __Marshaller_automation_UpkeepInfo = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Automation.UpkeepInfo.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Automation.InitializeInput> __Marshaller_automation_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Automation.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Automation.ReportInput> __Marshaller_automation_ReportInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Automation.ReportInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AetherLink.Contracts.Automation.RegisterUpkeepInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RegisterUpkeep = new aelf::Method<global::AetherLink.Contracts.Automation.RegisterUpkeepInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RegisterUpkeep",
        __Marshaller_automation_RegisterUpkeepInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeregisterUpkeep = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "DeregisterUpkeep",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Automation.UpkeepInfo> __Method_GetUpkeepInfo = new aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Automation.UpkeepInfo>(
        aelf::MethodType.View,
        __ServiceName,
        "GetUpkeepInfo",
        __Marshaller_aelf_Hash,
        __Marshaller_automation_UpkeepInfo);

    static readonly aelf::Method<global::AetherLink.Contracts.Automation.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::AetherLink.Contracts.Automation.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_automation_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Pause = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Pause",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Unpause = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Unpause",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOracleContractAddress = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOracleContractAddress",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRequestTypeIndex = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRequestTypeIndex",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetSubscriptionId = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetSubscriptionId",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AetherLink.Contracts.Automation.ReportInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Report = new aelf::Method<global::AetherLink.Contracts.Automation.ReportInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Report",
        __Marshaller_automation_ReportInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteCommitment = new aelf::Method<global::AElf.Types.Hash, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "DeleteCommitment",
        __Marshaller_aelf_Hash,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_IsPaused = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "IsPaused",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetOracleContractAddress = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOracleContractAddress",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetRequestTypeIndex = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRequestTypeIndex",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AElf.Types.Hash> __Method_GetCommitmentHash = new aelf::Method<global::AElf.Types.Hash, global::AElf.Types.Hash>(
        aelf::MethodType.View,
        __ServiceName,
        "GetCommitmentHash",
        __Marshaller_aelf_Hash,
        __Marshaller_aelf_Hash);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::AetherLink.Contracts.Automation.AutomationContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of AutomationContract</summary>
    // public abstract partial class AutomationContractBase : AElf.Sdk.CSharp.CSharpSmartContract<AetherLink.Contracts.Automation.AutomationContractState>
    // {
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RegisterUpkeep(global::AetherLink.Contracts.Automation.RegisterUpkeepInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty DeregisterUpkeep(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Automation.UpkeepInfo GetUpkeepInfo(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Initialize(global::AetherLink.Contracts.Automation.InitializeInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Pause(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Unpause(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetOracleContractAddress(global::AElf.Types.Address input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetRequestTypeIndex(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetSubscriptionId(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Report(global::AetherLink.Contracts.Automation.ReportInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteCommitment(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetAdmin(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.BoolValue IsPaused(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetOracleContractAddress(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetRequestTypeIndex(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Hash GetCommitmentHash(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    // }
    //
    // public static aelf::ServerServiceDefinition BindService(AutomationContractBase serviceImpl)
    // {
    //   return aelf::ServerServiceDefinition.CreateBuilder()
    //       .AddDescriptors(Descriptors)
    //       .AddMethod(__Method_RegisterUpkeep, serviceImpl.RegisterUpkeep)
    //       .AddMethod(__Method_DeregisterUpkeep, serviceImpl.DeregisterUpkeep)
    //       .AddMethod(__Method_GetUpkeepInfo, serviceImpl.GetUpkeepInfo)
    //       .AddMethod(__Method_Initialize, serviceImpl.Initialize)
    //       .AddMethod(__Method_Pause, serviceImpl.Pause)
    //       .AddMethod(__Method_Unpause, serviceImpl.Unpause)
    //       .AddMethod(__Method_SetOracleContractAddress, serviceImpl.SetOracleContractAddress)
    //       .AddMethod(__Method_SetRequestTypeIndex, serviceImpl.SetRequestTypeIndex)
    //       .AddMethod(__Method_SetSubscriptionId, serviceImpl.SetSubscriptionId)
    //       .AddMethod(__Method_Report, serviceImpl.Report)
    //       .AddMethod(__Method_DeleteCommitment, serviceImpl.DeleteCommitment)
    //       .AddMethod(__Method_GetAdmin, serviceImpl.GetAdmin)
    //       .AddMethod(__Method_IsPaused, serviceImpl.IsPaused)
    //       .AddMethod(__Method_GetOracleContractAddress, serviceImpl.GetOracleContractAddress)
    //       .AddMethod(__Method_GetRequestTypeIndex, serviceImpl.GetRequestTypeIndex)
    //       .AddMethod(__Method_GetCommitmentHash, serviceImpl.GetCommitmentHash).Build();
    // }

  }
}
#endregion

