// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: consumer_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AetherLink.Contracts.Consumer {

  #region Events
  public partial class PriceUpdated : aelf::IEvent<PriceUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<PriceUpdated> GetIndexed()
    {
      return new List<PriceUpdated>
      {
      };
    }

    public PriceUpdated GetNonIndexed()
    {
      return new PriceUpdated
      {
        From = From,
        To = To,
        RoundNumber = RoundNumber,
        UpdateAt = UpdateAt,
      };
    }
  }

  public partial class OracleFulfillmentHandled : aelf::IEvent<OracleFulfillmentHandled>
  {
    public global::System.Collections.Generic.IEnumerable<OracleFulfillmentHandled> GetIndexed()
    {
      return new List<OracleFulfillmentHandled>
      {
      };
    }

    public OracleFulfillmentHandled GetNonIndexed()
    {
      return new OracleFulfillmentHandled
      {
        RequestId = RequestId,
        RequestTypeIndex = RequestTypeIndex,
      };
    }
  }

  public partial class AdminTransferRequested : aelf::IEvent<AdminTransferRequested>
  {
    public global::System.Collections.Generic.IEnumerable<AdminTransferRequested> GetIndexed()
    {
      return new List<AdminTransferRequested>
      {
      };
    }

    public AdminTransferRequested GetNonIndexed()
    {
      return new AdminTransferRequested
      {
        From = From,
        To = To,
      };
    }
  }

  public partial class AdminTransferred : aelf::IEvent<AdminTransferred>
  {
    public global::System.Collections.Generic.IEnumerable<AdminTransferred> GetIndexed()
    {
      return new List<AdminTransferred>
      {
      };
    }

    public AdminTransferred GetNonIndexed()
    {
      return new AdminTransferred
      {
        From = From,
        To = To,
      };
    }
  }

  public partial class OracleRequestStarted : aelf::IEvent<OracleRequestStarted>
  {
    public global::System.Collections.Generic.IEnumerable<OracleRequestStarted> GetIndexed()
    {
      return new List<OracleRequestStarted>
      {
      };
    }

    public OracleRequestStarted GetNonIndexed()
    {
      return new OracleRequestStarted
      {
        SubscriptionId = SubscriptionId,
        RequestTypeIndex = RequestTypeIndex,
        SpecificData = SpecificData,
      };
    }
  }

  public partial class ControllerAdded : aelf::IEvent<ControllerAdded>
  {
    public global::System.Collections.Generic.IEnumerable<ControllerAdded> GetIndexed()
    {
      return new List<ControllerAdded>
      {
      };
    }

    public ControllerAdded GetNonIndexed()
    {
      return new ControllerAdded
      {
        Controllers = Controllers,
      };
    }
  }

  public partial class ControllerRemoved : aelf::IEvent<ControllerRemoved>
  {
    public global::System.Collections.Generic.IEnumerable<ControllerRemoved> GetIndexed()
    {
      return new List<ControllerRemoved>
      {
      };
    }

    public ControllerRemoved GetNonIndexed()
    {
      return new ControllerRemoved
      {
        Controllers = Controllers,
      };
    }
  }

  #endregion
  /// <summary>
  /// the contract definition: a gRPC service definition.
  /// </summary>
  public static partial class ConsumerContractContainer
  {
    static readonly string __ServiceName = "consumer.ConsumerContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.StartOracleRequestInput> __Marshaller_oracle_StartOracleRequestInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.StartOracleRequestInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.HandleOracleFulfillmentInput> __Marshaller_oracle_HandleOracleFulfillmentInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.HandleOracleFulfillmentInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.InitializeInput> __Marshaller_consumer_InitializeInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.InitializeInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.AddressList> __Marshaller_consumer_AddressList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.AddressList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Hash> __Marshaller_aelf_Hash = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Hash.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.OracleResponse> __Marshaller_oracle_OracleResponse = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.OracleResponse.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.LongList> __Marshaller_consumer_LongList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.LongList.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.PriceRoundData> __Marshaller_consumer_PriceRoundData = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.PriceRoundData.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int64Value> __Marshaller_google_protobuf_Int64Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int64Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AetherLink.Contracts.Consumer.HashList> __Marshaller_consumer_HashList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AetherLink.Contracts.Consumer.HashList.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::AetherLink.Contracts.Consumer.StartOracleRequestInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StartOracleRequest = new aelf::Method<global::AetherLink.Contracts.Consumer.StartOracleRequestInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "StartOracleRequest",
        __Marshaller_oracle_StartOracleRequestInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AetherLink.Contracts.Consumer.HandleOracleFulfillmentInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_HandleOracleFulfillment = new aelf::Method<global::AetherLink.Contracts.Consumer.HandleOracleFulfillmentInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "HandleOracleFulfillment",
        __Marshaller_oracle_HandleOracleFulfillmentInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AetherLink.Contracts.Consumer.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::AetherLink.Contracts.Consumer.InitializeInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_consumer_InitializeInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TransferAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "TransferAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AcceptAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AcceptAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AetherLink.Contracts.Consumer.AddressList, global::Google.Protobuf.WellKnownTypes.Empty> __Method_AddController = new aelf::Method<global::AetherLink.Contracts.Consumer.AddressList, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "AddController",
        __Marshaller_consumer_AddressList,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AetherLink.Contracts.Consumer.AddressList, global::Google.Protobuf.WellKnownTypes.Empty> __Method_RemoveController = new aelf::Method<global::AetherLink.Contracts.Consumer.AddressList, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "RemoveController",
        __Marshaller_consumer_AddressList,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetOracleContract = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetOracleContract",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetDataFeedsRequestTypeIndex = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetDataFeedsRequestTypeIndex",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetVrfRequestTypeIndex = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetVrfRequestTypeIndex",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AetherLink.Contracts.Consumer.AddressList> __Method_GetController = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AetherLink.Contracts.Consumer.AddressList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetController",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_consumer_AddressList);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Consumer.OracleResponse> __Method_GetOracleResponse = new aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Consumer.OracleResponse>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOracleResponse",
        __Marshaller_aelf_Hash,
        __Marshaller_oracle_OracleResponse);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetOracleContract = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetOracleContract",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Consumer.LongList> __Method_GetPriceList = new aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Consumer.LongList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPriceList",
        __Marshaller_aelf_Hash,
        __Marshaller_consumer_LongList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AetherLink.Contracts.Consumer.PriceRoundData> __Method_GetLatestPriceRoundData = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AetherLink.Contracts.Consumer.PriceRoundData>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLatestPriceRoundData",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_consumer_PriceRoundData);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value> __Method_GetLatestRound = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int64Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLatestRound",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int64Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AetherLink.Contracts.Consumer.PriceRoundData> __Method_GetPriceRoundData = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int64Value, global::AetherLink.Contracts.Consumer.PriceRoundData>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPriceRoundData",
        __Marshaller_google_protobuf_Int64Value,
        __Marshaller_consumer_PriceRoundData);

    static readonly aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Consumer.HashList> __Method_GetRandomHashList = new aelf::Method<global::AElf.Types.Hash, global::AetherLink.Contracts.Consumer.HashList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRandomHashList",
        __Marshaller_aelf_Hash,
        __Marshaller_consumer_HashList);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetDataFeedsRequestTypeIndex = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetDataFeedsRequestTypeIndex",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value> __Method_GetVrfRequestTypeIndex = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Int32Value>(
        aelf::MethodType.View,
        __ServiceName,
        "GetVrfRequestTypeIndex",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Int32Value);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AetherLink.Contracts.Consumer.ConsumerContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::AetherLink.Contracts.Consumer.RequestInterfaceReflection.Descriptor.Services[0],
          global::AetherLink.Contracts.Consumer.ConsumerContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

    /// <summary>Base class for the contract of ConsumerContract</summary>
    // public abstract partial class ConsumerContractBase : AElf.Sdk.CSharp.CSharpSmartContract<AetherLink.Contracts.Consumer.ConsumerContractState>
    // {
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty StartOracleRequest(global::AetherLink.Contracts.Consumer.StartOracleRequestInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty HandleOracleFulfillment(global::AetherLink.Contracts.Consumer.HandleOracleFulfillmentInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty Initialize(global::AetherLink.Contracts.Consumer.InitializeInput input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty TransferAdmin(global::AElf.Types.Address input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AcceptAdmin(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty AddController(global::AetherLink.Contracts.Consumer.AddressList input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty RemoveController(global::AetherLink.Contracts.Consumer.AddressList input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetOracleContract(global::AElf.Types.Address input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetDataFeedsRequestTypeIndex(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Empty SetVrfRequestTypeIndex(global::Google.Protobuf.WellKnownTypes.Int32Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetAdmin(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Consumer.AddressList GetController(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Consumer.OracleResponse GetOracleResponse(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AElf.Types.Address GetOracleContract(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Consumer.LongList GetPriceList(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Consumer.PriceRoundData GetLatestPriceRoundData(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int64Value GetLatestRound(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Consumer.PriceRoundData GetPriceRoundData(global::Google.Protobuf.WellKnownTypes.Int64Value input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::AetherLink.Contracts.Consumer.HashList GetRandomHashList(global::AElf.Types.Hash input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetDataFeedsRequestTypeIndex(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    //   public virtual global::Google.Protobuf.WellKnownTypes.Int32Value GetVrfRequestTypeIndex(global::Google.Protobuf.WellKnownTypes.Empty input)
    //   {
    //     throw new global::System.NotImplementedException();
    //   }
    //
    // }
    //
    // public static aelf::ServerServiceDefinition BindService(ConsumerContractBase serviceImpl)
    // {
    //   return aelf::ServerServiceDefinition.CreateBuilder()
    //       .AddDescriptors(Descriptors)
    //       .AddMethod(__Method_StartOracleRequest, serviceImpl.StartOracleRequest)
    //       .AddMethod(__Method_HandleOracleFulfillment, serviceImpl.HandleOracleFulfillment)
    //       .AddMethod(__Method_Initialize, serviceImpl.Initialize)
    //       .AddMethod(__Method_TransferAdmin, serviceImpl.TransferAdmin)
    //       .AddMethod(__Method_AcceptAdmin, serviceImpl.AcceptAdmin)
    //       .AddMethod(__Method_AddController, serviceImpl.AddController)
    //       .AddMethod(__Method_RemoveController, serviceImpl.RemoveController)
    //       .AddMethod(__Method_SetOracleContract, serviceImpl.SetOracleContract)
    //       .AddMethod(__Method_SetDataFeedsRequestTypeIndex, serviceImpl.SetDataFeedsRequestTypeIndex)
    //       .AddMethod(__Method_SetVrfRequestTypeIndex, serviceImpl.SetVrfRequestTypeIndex)
    //       .AddMethod(__Method_GetAdmin, serviceImpl.GetAdmin)
    //       .AddMethod(__Method_GetController, serviceImpl.GetController)
    //       .AddMethod(__Method_GetOracleResponse, serviceImpl.GetOracleResponse)
    //       .AddMethod(__Method_GetOracleContract, serviceImpl.GetOracleContract)
    //       .AddMethod(__Method_GetPriceList, serviceImpl.GetPriceList)
    //       .AddMethod(__Method_GetLatestPriceRoundData, serviceImpl.GetLatestPriceRoundData)
    //       .AddMethod(__Method_GetLatestRound, serviceImpl.GetLatestRound)
    //       .AddMethod(__Method_GetPriceRoundData, serviceImpl.GetPriceRoundData)
    //       .AddMethod(__Method_GetRandomHashList, serviceImpl.GetRandomHashList)
    //       .AddMethod(__Method_GetDataFeedsRequestTypeIndex, serviceImpl.GetDataFeedsRequestTypeIndex)
    //       .AddMethod(__Method_GetVrfRequestTypeIndex, serviceImpl.GetVrfRequestTypeIndex).Build();
    // }

  }
}
#endregion

