// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: coordinator_contract.proto
// </auto-generated>
// Original file comments:
// the version of the language, use proto3 for contracts
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Coordinator {

  #region Events
  public partial class AdminTransferRequested : aelf::IEvent<AdminTransferRequested>
  {
    public global::System.Collections.Generic.IEnumerable<AdminTransferRequested> GetIndexed()
    {
      return new List<AdminTransferRequested>
      {
      };
    }

    public AdminTransferRequested GetNonIndexed()
    {
      return new AdminTransferRequested
      {
        From = From,
        To = To,
      };
    }
  }

  public partial class AdminTransferred : aelf::IEvent<AdminTransferred>
  {
    public global::System.Collections.Generic.IEnumerable<AdminTransferred> GetIndexed()
    {
      return new List<AdminTransferred>
      {
      };
    }

    public AdminTransferred GetNonIndexed()
    {
      return new AdminTransferred
      {
        From = From,
        To = To,
      };
    }
  }

  public partial class Paused : aelf::IEvent<Paused>
  {
    public global::System.Collections.Generic.IEnumerable<Paused> GetIndexed()
    {
      return new List<Paused>
      {
      };
    }

    public Paused GetNonIndexed()
    {
      return new Paused
      {
        Account = Account,
      };
    }
  }

  public partial class Unpaused : aelf::IEvent<Unpaused>
  {
    public global::System.Collections.Generic.IEnumerable<Unpaused> GetIndexed()
    {
      return new List<Unpaused>
      {
      };
    }

    public Unpaused GetNonIndexed()
    {
      return new Unpaused
      {
        Account = Account,
      };
    }
  }

  public partial class RequestSent : aelf::IEvent<RequestSent>
  {
    public global::System.Collections.Generic.IEnumerable<RequestSent> GetIndexed()
    {
      return new List<RequestSent>
      {
      };
    }

    public RequestSent GetNonIndexed()
    {
      return new RequestSent
      {
        RequestId = RequestId,
        RequestingContract = RequestingContract,
        RequestingInitiator = RequestingInitiator,
        Commitment = Commitment,
      };
    }
  }

  public partial class Reported : aelf::IEvent<Reported>
  {
    public global::System.Collections.Generic.IEnumerable<Reported> GetIndexed()
    {
      return new List<Reported>
      {
      };
    }

    public Reported GetNonIndexed()
    {
      return new Reported
      {
        RequestId = RequestId,
        Transmitter = Transmitter,
      };
    }
  }

  public partial class RequestTypeIndexSet : aelf::IEvent<RequestTypeIndexSet>
  {
    public global::System.Collections.Generic.IEnumerable<RequestTypeIndexSet> GetIndexed()
    {
      return new List<RequestTypeIndexSet>
      {
      };
    }

    public RequestTypeIndexSet GetNonIndexed()
    {
      return new RequestTypeIndexSet
      {
        RequestTypeIndex = RequestTypeIndex,
      };
    }
  }

  public partial class CommitmentDeleted : aelf::IEvent<CommitmentDeleted>
  {
    public global::System.Collections.Generic.IEnumerable<CommitmentDeleted> GetIndexed()
    {
      return new List<CommitmentDeleted>
      {
      };
    }

    public CommitmentDeleted GetNonIndexed()
    {
      return new CommitmentDeleted
      {
        RequestId = RequestId,
      };
    }
  }

  #endregion
}
#endregion

